ads:
        ADS1015: true
        ADS1115: false
button:
        shutdown: [8, 2] #BCM GPIO Pin
        monitor: [7, 1] #BCM GPIO Pin

controller:
        #button_name : [pin, keybaord_value]
        A: [23, 'a']
        B: [15, 'b']
        X: [16, 'x']
        Y: [10, 'y']
        UP: [11, 'up']
        DOWN: [8, 'down']
        LEFT: [25, 'left']
        RIGHT: [26, 'right']
        START: [9, 'enter']
        SELECT: [11, 'shift']
        ESCAPE: [10, 'esc']
        L1TRIGGER: [1, 'w']
        R1TRIGGER: [4, 'e']
        L2TRIGGER: [6, 'q']
        R2TRIGGER: [14, 'r']
        #implement joystick

        
votage_reading: 
        # number of seconds to get the average
        seconds: 1
        # refresh rate 
        sleep: 0.2

agent:
        pidfile: '/tmp/battery-monitor.pid'

converstion-ratio: 0.01275

png:
        x: 1200 
        y: 10
        path: "/home/pi/BatteryMonitor/Pngview"
        icon: "/home/pi/BatteryMonitor/icons"
gain: 1

icon-timeout: 3

