ads:
        ADS1015: true
        ADS1115: false
button:
        shutdown: [8, 2, false] #BCM GPIO Pin
        monitor: [7, 1, true] #BCM GPIO Pin
        
votage_reading: 
        # number of seconds to get the average
        seconds: 1
        # refresh rate 
        sleep: 0.2

agent:
        pidfile: '/tmp/battery-monitor.pid'

converstion-ratio: 0.01275

png:
        x: 1200 
        y: 10
        path: "/home/pi/BatteryMonitor/Pngview"
        icon: "/home/pi/BatteryMonitor/icons"
gain: 1

icon-timeout: 3

